#version: '3.8'
#
#services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"   # AMQP poort voor communicatie
#      - "15672:15672" # Management interface
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq  # Gedeelde lokale testdata
#    networks:
#      - mijn-network
#
#  microservice:
#    build: .
#    container_name: microservice
#    depends_on:
#      - rabbitmq
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
#      - RABBITMQ_USERNAME=guest
#      - RABBITMQ_PASSWORD=guest
#    ports:
#      - "30000:30000"  # Poort 30000 microservice
#    networks:
#      - mijn-network
#
#networks:
#  mijn-network:
#    driver: bridge
#
#volumes:
#  rabbitmq_data:

version: '3.8'

services:
  microservice:
    build: .
    container_name: microservice
    environment:
      - RABBITMQ_HOST=localhost  # host name veranderen voor de vm school.
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest  # name change vm van de school
      - RABBITMQ_PASSWORD=guest  # pass change vm van de school
    ports:
      - "30000:30000"  # Poort 30000 voor de microservice
    networks:
      - mijn-network

networks:
  mijn-network:
    driver: bridge