version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    ports:
      - "5672:5672"    # AMQP-poort
      - "15672:15672"  # Web UI
    networks:
      - rabbitmq_project_network
    restart: unless-stopped

networks:
  rabbitmq_project_network:
    external: false
#docker-compose -f docker-compose.rabbitmq.yml up
#docker-compose up --build  voor de microserver
# of
#sudo docker-compose -f docker-compose.rabbitmq.yml up
#sudo docker-compose up --build voor de microserver
#local = http://localhost:15672
# user/pass = guest