name: E2E Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    env:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SALESFORCE_USERNAME: ${{ secrets.SF_USERNAME }}
      SALESFORCE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      SALESFORCE_TOKEN: ${{ secrets.SF_TOKEN }}
      SALESFORCE_LOGIN_URL: ${{ secrets.SF_LOGIN }}

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3

      - name: 🧱 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🐇 Wacht op RabbitMQ
        run: |
          for i in {1..15}; do
            nc -z rabbitmq 5672 && echo "✅ RabbitMQ is klaar" && exit 0
            echo "⏳ Wachten op RabbitMQ ($i/15)..."
            sleep 3
          done
          echo "❌ RabbitMQ kwam niet op tijd op" && exit 1

      - name: 🔐 Controleer Salesforce secrets
        run: |
          [ -z "$SALESFORCE_USERNAME" ] && echo "❌ SALESFORCE_USERNAME ontbreekt" && exit 1
          echo "✅ Secrets aanwezig"

      - name: 🧪 Run E2E tests
        run: npm test -- tests/e2e/cdcListener.e2e.test.js
