name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-jsforce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: test-jsforce
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
          # Navigate to the app directory
          cd ~/crmV2

          # Pull the latest code from the main branch
          git pull origin main

          # Stop and remove the existing container
          docker stop CRM || true
          docker rm CRM || true

          # Rebuild the container with the latest code
          docker build -t CRM:latest .

          # Run the new container
          docker run -d --name CRM CRM:latest
          EOF
