name: CI/CD Pipeline

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job to run tests (placeholder for now)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: echo "⚠️ No test setup yet, skipping"
        # Uncomment and replace with actual test command when ready
        # run: npm test
      - name: Test Docker Compose
        run: |
          docker compose up -d        # Fix: Use -d for detached mode
          sleep 10                    # Wait for containers to start
          docker ps                   # Verify running containers
          docker compose down         # Clean up

  # Job to build and deploy the Docker image
  deploy:
    name: Deploy To Server
    needs: test
    runs-on: ubuntu-latest
    environment: environment

    steps:
      - name: Setup SSH Connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          debug: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ ! -d "~/crmV2" ]; then
              mkdir -p ~/crmV2
              git clone https://github.com/IntegrationProject1/CRM.git ~/crmV2
            fi
            cd ~/crmV2
            git pull origin main
            docker compose pull crm-service
            docker compose up -d --no-deps --build crm-service
            docker image prune -f 
