name: Validator for Main or Development

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
  
      - name: Install dependencies
        run: npm ci
  
      - name: Run tests
        run: |
          # echo "⚠️ No test setup, skipping"
          # Uncomment the line below to run tests when ready
          npm test
